package me.marin.calcoverlay.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.Getter;
import me.marin.calcoverlay.CalcOverlay;
import me.marin.calcoverlay.util.CalcOverlayUtil;

import javax.swing.*;
import java.awt.*;

public class InvalidMeasurementGUI {

    @Getter
    private JPanel mainPanel;

    public InvalidMeasurementGUI() {
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(5, 20, 5, 20);

        addLabel("Could not determine the stronghold chunk.", gbc);
        gbc.insets.bottom = 20;
        addLabel("You probably misread one of the eyes.", gbc);
        gbc.insets.bottom = 5;
    }

    private void addLabel(String text, GridBagConstraints gbc) {
        JLabel label = CalcOverlayUtil.setupJLabel(text);
        mainPanel.add(label, gbc);
        gbc.anchor = GridBagConstraints.WEST;
        gbc.gridy++;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
